server:
  port: 8084
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
        - id: HOTELSERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/api/hotels/**,/api/staffs/**
        - id: RATINGSERVICE
          uri: http://localhost:8083
          predicates:
            - Path=/api/ratings/**
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 172.30.112.1
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
logging:
  level:
    com.netflix.eureka: DEBUG
    org.springframework.cloud.gateway: DEBUG



#okta configuration for api gateway
#
#okta:
#  oauth2:
#    issuer: https://dev-77584981.okta.com/oauth2/default
#    audience: api://default
#    client-id: 0oa7w65a24Px9Oyms5d7
#    client-secret: JfsTTqODW21uapbbhKjW42sGzjcNs86GN7WL5dfU
#    scopes: openid, profile, email, offline_access