server:
  port: 8082
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/microservice'
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: HOTEl-SERVICE
    eureka:
      instance:
        prefer-ip-address: true
        ip-address: 172.30.112.1
        hostname: localhost
      client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
          defaultZone: 'http://localhost:8761/eureka/'
