server:
  port: 8085
spring:
    cloud:
        config:
          server:
            git:
              uri: https://github.com/MadhuMarrapu/microservice-config.git
              clone-on-start: true
